version: "3.9"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dga
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/dga"
    command: >
      sh -c "
        npx prisma migrate deploy ||
        npx prisma db push &&
        npx prisma db seed &&
        npx tsx src/index.ts
      "

volumes:
  db_data:
